// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMLbCWfbNiNSIH8S5YmtSFn8VRzGWTZ1Y',
    appId: '1:776429497842:web:055f9fbfc25c7ffa0c4f6b',
    messagingSenderId: '776429497842',
    projectId: 'stockpredicitonsss-ba355',
    authDomain: 'stockpredicitonsss-ba355.firebaseapp.com',
    storageBucket: 'stockpredicitonsss-ba355.firebasestorage.app',
    measurementId: 'G-2TVY108CYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQu5rwFHHR0Af1FDnhSvapw1mnd8_Fnk',
    appId: '1:776429497842:android:63a4752d3041fd610c4f6b',
    messagingSenderId: '776429497842',
    projectId: 'stockpredicitonsss-ba355',
    storageBucket: 'stockpredicitonsss-ba355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqSlNPqAt5DjmSH4yW5HP91IjxdDy-dLM',
    appId: '1:776429497842:ios:ae6d3d5de67d99370c4f6b',
    messagingSenderId: '776429497842',
    projectId: 'stockpredicitonsss-ba355',
    storageBucket: 'stockpredicitonsss-ba355.firebasestorage.app',
    iosBundleId: 'com.example.stockpredicitonsss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqSlNPqAt5DjmSH4yW5HP91IjxdDy-dLM',
    appId: '1:776429497842:ios:ae6d3d5de67d99370c4f6b',
    messagingSenderId: '776429497842',
    projectId: 'stockpredicitonsss-ba355',
    storageBucket: 'stockpredicitonsss-ba355.firebasestorage.app',
    iosBundleId: 'com.example.stockpredicitonsss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMLbCWfbNiNSIH8S5YmtSFn8VRzGWTZ1Y',
    appId: '1:776429497842:web:eb5a50fc28b6556b0c4f6b',
    messagingSenderId: '776429497842',
    projectId: 'stockpredicitonsss-ba355',
    authDomain: 'stockpredicitonsss-ba355.firebaseapp.com',
    storageBucket: 'stockpredicitonsss-ba355.firebasestorage.app',
    measurementId: 'G-Q9YKSXQ7EJ',
  );

}